"""Markdown generation for codemap output."""

from pathlib import Path

from .config import Config
from .modules import Module
from .parser import get_parser_for_file, FileStructure
from .llm import LLMClient


class MapGenerator:
    """Generates markdown documentation for modules."""
    
    def __init__(self, config: Config, codemap_path: Path):
        self.config = config
        self.codemap_path = codemap_path
        self.modules_path = codemap_path / "modules"
        self.llm = LLMClient(config)
    
    def generate_module(self, module: Module) -> Path:
        """Generate markdown documentation for a module.
        
        Returns:
            Path to the generated markdown file.
        """
        # Parse all files in the module
        structures: list[FileStructure] = []
        for path, _ in module.files:
            parser = get_parser_for_file(path)
            if parser:
                try:
                    structure = parser.parse(path)
                    structures.append(structure)
                except Exception:
                    # Skip files that fail to parse
                    pass
        
        # Generate summary using LLM
        content = self.llm.summarize_module(module, structures)
        
        # Write to file
        # Convert module name to filename (e.g., "src/parser" -> "src_parser.md")
        filename = module.name.replace("/", "_").replace("\\", "_") + ".md"
        output_path = self.modules_path / filename
        
        self.modules_path.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content)
        
        return output_path
    
    def generate_overview(self) -> Path:
        """Generate overview.md that indexes all modules.
        
        Returns:
            Path to the generated overview file.
        """
        overview_path = self.codemap_path / "overview.md"
        
        # Collect all module files
        module_files = sorted(self.modules_path.glob("*.md"))
        
        lines = [
            "# Code Map Overview",
            "",
            "This document provides a high-level overview of the codebase architecture.",
            "",
            "## Modules",
            "",
        ]
        
        for module_file in module_files:
            # Extract first line (title) and purpose from module file
            content = module_file.read_text()
            module_lines = content.split("\n")
            
            # Get module name from first heading
            name = module_file.stem.replace("_", "/")
            
            # Find purpose line
            purpose = ""
            for line in module_lines:
                if line.startswith("**Purpose**:"):
                    purpose = line.replace("**Purpose**:", "").strip()
                    break
            
            rel_path = f"modules/{module_file.name}"
            lines.append(f"- [{name}]({rel_path}) – {purpose}")
        
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("*Generated by Cartographer*")
        
        overview_path.write_text("\n".join(lines))
        return overview_path
